version: 2.1

orbs:
  node: circleci/node@4.1.0
  browser-tools: circleci/browser-tools@1.2.1

defaults: &defaults
  docker:
    - image: cimg/node:14.18.2-browsers
  executor:
      name: node/default
      tag: '14.18.2'

jobs:
  node-tests:
    <<: *defaults
    steps:
      - run:
          name: install package dependencies
          command: |
            sudo apt-get update -q
            sudo apt-get install -q -y libasound2-dev
      - checkout
      - node/install:
          install-yarn: false
          install-npm: true
      - node/install-packages:
          app-dir: ~/project
          pkg-manager: npm
          cache-version: v1
      - run:
          name: run tests
          command: npm test

  publish:
    docker:
      - image: node:14-alpine
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Publish
          command: npm publish

workflows:
  version: 2
  test_and_publish:
    jobs:
      - node-tests:
          filters:
            tags:
              only:
                - /.*/
      - publish:
          context:
            - NPM-CONFIG
          requires:
            - node-tests
          filters:
            branches:
              ignore:
                - /.*/
            tags:
              only:
                - /^v.*/
